### ISSUE TITLE
Not including sources of libs which are not directly dependent of the app

### ISSUE THREAD

**Issue by ak274** [koliveira15/nx-sonarqube#11]
While running `nx run my-app:sonar` it only includes libs which are direct dependencies of `my-app`.

For example if `my-app `has 2 libs `lib-a` and `lib-b `which are directly imported in `my-app` the command will only detect these 2 libs. 
If these two libs further has dependencies scanner is not able to include them as dependent to analyze code. It should scan them too as they are also being used as dependency indirectly by `my-app`.

In actual application I have configured test to run with deps  when I'm running `nx test my-app`,  with  it shows 98 deps.

But with sonar I can see it only detect 32 direct Deps. Not detecting libs which are dependent of other libs which are not direct dependent.  

    ```
nx : 14.1.9
   @nrwl/angular : 14.1.9
   @nrwl/cypress : 14.1.9
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.9
   @nrwl/eslint-plugin-nx : 14.1.9
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.9
   @nrwl/js : Not Found
   @nrwl/linter : 14.1.9
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.9
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.9
   typescript : 4.6.3
   ---------------------------------------
   Community plugins:
         @ngrx/effects: 13.1.0
         @ngrx/entity: 13.1.0
         @ngrx/router-store: 13.1.0
         @ngrx/store: 13.1.0
         rxjs: 6.6.7
         @ngrx/schematics: 13.1.0
         @ngrx/store-devtools: 13.1.0
```

**Comment by koliveira15** [comment]
@ak274 thank you for opening an issue. I will fix this 👍

**Comment by ak274** [comment]
@koliveira15 Any update on this issue. Without resolving this issue the plugin is not useful.

**Comment by koliveira15** [comment]
@ak274 Can you try version 2.0.1

**Comment by ak274** [comment]
after updating to latest version.

i'm facing this error while execution:--

ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: Failed to parse JSON in SONARQUBE_SCANNER_PARAMS environment variable
        at org.sonarsource.scanner.api.Utils.loadEnvironmentProperties(Utils.java:65)
        at org.sonarsource.scanner.cli.Conf.loadEnvironmentProperties(Conf.java:88)
        at org.sonarsource.scanner.cli.Conf.loadGlobalProperties(Conf.java:95)
        at org.sonarsource.scanner.cli.Conf.properties(Conf.java:60)
        at org.sonarsource.scanner.cli.Main.execute(Main.java:69)
        at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.UnsupportedOperationException: Not a string: false
        at org.sonarsource.scanner.api.internal.shaded.minimaljson.JsonValue.asString(JsonValue.java:384)
        at org.sonarsource.scanner.api.Utils.loadEnvironmentProperties(Utils.java:61)
        ... 5 more
ERROR:
