### ISSUE TITLE
Support sonarqube-scanner v4

### ISSUE THREAD

**Issue by Tommy228** [koliveira15/nx-sonarqube#118]
### Which scope/s are relevant/related to the feature request?

@koliveira15/nx-sonarqube

### Information

[sonarqube-scanner](https://www.npmjs.com/package/sonarqube-scanner) has a new major version (v4) however `nx-sonarqube` does not support it currently. The executor fails with the following error
```
TypeError: sonarQubeScanner.async is not a function
    at node_modules/@koliveira15/nx-sonarqube/src/executors/scan/utils/utils.js:154:48
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I think `async` needs to be replaced with `scan`.

### I would be willing to submit a PR to provide this feature

- [X] Yes
- [ ] No

**Comment by gcko** [comment]
@Tommy228 once PPR #117 is checked and merged into main, I can take a look at updating the version of `sonarqube-scanner` to latest. It will require updates to the tests as well
