### ISSUE TITLE
Gitlab CI is not recognizing the git command used to retrieve branch name

### ISSUE THREAD

**Issue by ak274** [koliveira15/nx-sonarqube#14]
I'm using this scan executer in Gitlab CI where its not able to recognize the branch names.Please refer the image.

https://github.com/koliveira15/nx-sonarqube/blob/d75fcf10e95db811250f0ea69981e768cb47b7fb/packages/nx-sonarqube/src/executors/scan/utils/utils.ts#L105

![image](https://user-images.githubusercontent.com/16129430/196628475-5764f8d9-9871-4f63-887c-25608dca1532.png)

**Comment by ak274** [comment]
Following might help to understand why its not working in Gitlab CICD.
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4557

**Comment by koliveira15** [comment]
@ak274 seems like the issue is specific to Gitlab runner. Handling every type of CI environment is not in scope for the plugin. I would be open to changing the branches parameter to branch. That way consumers can get their own branch, respective of their CI environment.

**Comment by ak274** [comment]
I have observed that if you remove sonar.branch.name param from the scanner function altogether.. the GitLab CI automatically detect branch name and pull requests.

**Comment by tstackhouse** [comment]
This behaviour also happens in GitHub's CI/CD pipelines. Running with `branches: false` the scanner tries to autoconfigure, but fails because `sonar.branch.name` is still passed, even though the value is `''`, resulting in the following:

```
...
INFO: Load project branches
INFO: Load project branches (done) | time=108ms
INFO: Load project pull requests
INFO: Load project pull requests (done) | time=113ms
INFO: Load branch configuration
INFO: Detected branch/PR in 'GitHub Action'
INFO: Auto-configuring pull request '2287'
INFO: ------------------------------------------------------------------------
INFO: EXECUTION FAILURE
INFO: ------------------------------------------------------------------------
INFO: Total time: 15.413s
ERROR: Error during SonarScanner execution
ERROR: A pull request analysis cannot have the branch analysis parameter 'sonar.branch.name'
ERROR: 
INFO: Final Memory: 6M/24M
INFO: ------------------------------------------------------------------------
```

**Comment by tstackhouse** [comment]
Opened PR #21 to omit the param if the option is false or unset.

**Comment by koliveira15** [comment]
@tstackhouse your PR has been published under version 2.1.1

**Comment by tstackhouse** [comment]
Sweet! Thank you for pulling in my change. I’ll give it a try on Monday :)

**Comment by tstackhouse** [comment]
Just to follow up, I pulled in the update and it worked like a charm :D The PR detection is now working perfectly in GitHub CI.  Thanks again!
