### ISSUE TITLE
Support scope parameters

### ISSUE THREAD

**Issue by jwmickey** [koliveira15/nx-sonarqube#16]
Sonar provides the ability to [Narrow the Focus](https://docs.sonarqube.org/latest/project-administration/narrowing-the-focus/) by setting scope for source and test paths.  This helps, for example, avoid including test files in coverage reports.  

If your spec files live along-side the files they test, you may want to set these params:

    'sonar.tests': paths.sources()
    'sonar.test.inclusions': '**/*.spec.ts'

Adding `testInclusions` as a string param would be straight forward.  Assuming `sonar.tests` is always the same as sources might not serve every use case.  An alternative approach could be:

    interface ScanExecutorSchema {
      // existing properties not included for brevity
      testInclusions?: string;
      tests?: string;
      testsPathsFromSources?: boolean;
    }

... and then determine what to send to the scanner like:

    'sonar.tests': options.testPathsFromSources ? paths.sources : options.tests,
    'sonar.test.inclusions': options.testInclusions

**Comment by koliveira15** [comment]
Published Version 2.1.0
