### ISSUE TITLE
Detect coverageDirectory in project json

### ISSUE THREAD

**Issue by albthali** [koliveira15/nx-sonarqube#26]
The current implementation of the plugin detects jest config files defined in the project and tries to parse their coverageDirectory to add any coverage files in these directory. However, jest config is not the only place that could have the coverage directory. Nx allows you to define some test options, including the[ coverage directory](https://nx.dev/packages/jest/executors/jest#coverageDirectory). 

The [PR](https://github.com/koliveira15/nx-sonarqube/pull/25) adds some changes that allows the plugin to detect the coverage directory in the project json and uses it to add coverage files to the sonar scan.

**Comment by koliveira15** [comment]
Published in version 2.2.0
