### ISSUE TITLE
Allow extra options and environment variables to be passed to the scanner 

### ISSUE THREAD

**Issue by albthali** [koliveira15/nx-sonarqube#28]
The current implementation allows the user a select variables to be passed to the scanner. This is a problem is the scanner has a plethora of variables that needs to be defined for different cases.

This [PR](https://github.com/koliveira15/nx-sonarqube/pull/27) allows the user add extra options via an extra object in the project json or via environment variables.

**Comment by koliveira15** [comment]
Closed by [#27](https://github.com/koliveira15/nx-sonarqube/pull/27)

**Comment by koliveira15** [comment]
Published in version 2.2.0
