### ISSUE TITLE
Can't override sonar.typescript.tsconfigPath

### ISSUE THREAD

**Issue by jahusa02** [koliveira15/nx-sonarqube#38]
Hey,

i want to override the tsconfigPath for each app. When I set sonar.typescript.tsconfigPath in the "extra" key of the config it will always use the tsconfig.base.json

https://github.com/koliveira15/nx-sonarqube/blob/e06e3a3731b0217fa0cdc546b24f9ffe59d697cb/packages/nx-sonarqube/src/executors/scan/utils/utils.ts#L180

here you explicit use the base config. Is there any reason why you choose to not let that variable be customized?

**Comment by koliveira15** [comment]
@jahusa02 apologies for the delay. 

There is no reason why it's not customizable. tsconfig.base.json is just the root tsconfig with has alias paths. I will open a PR for the tsconfigPath to be included in the executor schema

**Comment by jahusa02** [comment]
Thanks!
