### ISSUE TITLE
Include @nx/devkit as a dependency

### ISSUE THREAD

**Issue by isaacplmann** [koliveira15/nx-sonarqube#40]
This plugin doesn't have an Nx version listed in the [Nx Plugin Registry](https://nx.dev/extending-nx/registry) because the plugin doesn't include `@nx/devkit` as a dependency.  Could you please release a version that fixes that?

Thanks,
Isaac (Nx Team)

**Comment by koliveira15** [comment]
@isaacplmann thanks for reaching out. I assuming you want to see the @nx/devkit package explicitly [here](https://github.com/koliveira15/nx-sonarqube/blob/main/packages/nx-sonarqube/package.json)? 

Two things:
1. My plugin does depend on [@nx/devkit ](https://github.com/koliveira15/nx-sonarqube/blob/main/packages/nx-sonarqube/src/executors/scan/executor.ts#L2) here but when I build using the tsc executor, the dependency is not added automatically to the built package.json.
2. Can the plugin registry logic perform a "npm view package-name" or something to check built dependencies? Id rather not maintain that version explicitly in the lib's package.json and let nx migrations update the root and have the tsc executor add that dependency for me.
