### ISSUE TITLE
Failed to find apps/<app-name>/package.json when run the command

### ISSUE THREAD

**Issue by destnguyxn** [koliveira15/nx-sonarqube#46]
Hello, 

When I try to run the plugin using `nx run-many`, the plugin try to find the `package.json` in the dỉectory of each application end raise an error `ENOENT: no such file or directory` since there is only `project.json`

It is not make the command failed but seem annoying when I try to read the console log. Could you check this please?

Thank you

**Comment by gcko** [comment]
@koliveira15 The issue for me is that I define a `package.json` at the root level, and not for each application. Reading the code in [utils.js](https://github.com/koliveira15/nx-sonarqube/blob/7607b1e2ee9ee32a5ecac906a75ddbc9e2a897fc/packages/nx-sonarqube/src/executors/scan/utils/utils.ts#L220), I notice that it is expecting each application to have a `package.json` file. I suggest you add a fallback to check the root directory for a `package.json` file and use the version from there

**Comment by gcko** [comment]
@destnguyxn a "quick fix" to remove the error is to add `projectVersion` to your `sonar` options:

```JSON
{
...
"sonar": {
      "executor": "@koliveira15/nx-sonarqube:scan",
      "options": {
        "projectVersion": "1.0",
        ...
      }
    }
  }
}
```

**Comment by destnguyxn** [comment]
@gcko the plugin does have a fallback to the root directory when not found the `package.json` , it just the error message seems annoying and may cause misunderstanding.

Thank you for the quick fix 😄

**Comment by gcko** [comment]
@destnguyxn ah! well in that case, the solution would be to change it from an ERROR to an INFO message, or WARN
